//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto1DB : DbContext
    {
        public Proyecto1DB()
            : base("name=Proyecto1DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjuntosXPuntoDB> AdjuntosXPuntoDBs { get; set; }
        public virtual DbSet<ComentariosDB> ComentariosDBs { get; set; }
        public virtual DbSet<ComentariosXPuntoDB> ComentariosXPuntoDBs { get; set; }
        public virtual DbSet<ConsejoDB> ConsejoDBs { get; set; }
        public virtual DbSet<DocXSesionDB> DocXSesionDBs { get; set; }
        public virtual DbSet<Miembros_ConsejoDB> Miembros_ConsejoDB { get; set; }
        public virtual DbSet<Miembros_SesionDB> Miembros_SesionDB { get; set; }
        public virtual DbSet<MiembrosDB> MiembrosDBs { get; set; }
        public virtual DbSet<Punto_AgendaDB> Punto_AgendaDB { get; set; }
        public virtual DbSet<PuntosXSesionDB> PuntosXSesionDBs { get; set; }
        public virtual DbSet<SesionDB> SesionDBs { get; set; }
        public virtual DbSet<Solicitudes_PuntosDB> Solicitudes_PuntosDB { get; set; }
    }
}
