//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Proyecto1DB : DbContext
    {
        public Proyecto1DB()
            : base("name=Proyecto1DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActualizacionesMiembrosDB> ActualizacionesMiembrosDBs { get; set; }
        public virtual DbSet<AdjuntosXPuntoDB> AdjuntosXPuntoDBs { get; set; }
        public virtual DbSet<ComentariosDB> ComentariosDBs { get; set; }
        public virtual DbSet<ComentariosXPuntoDB> ComentariosXPuntoDBs { get; set; }
        public virtual DbSet<ConsejoDB> ConsejoDBs { get; set; }
        public virtual DbSet<DocXSesionDB> DocXSesionDBs { get; set; }
        public virtual DbSet<HistorialMiembrosDB> HistorialMiembrosDBs { get; set; }
        public virtual DbSet<Miembros_ConsejoDB> Miembros_ConsejoDB { get; set; }
        public virtual DbSet<Miembros_SesionDB> Miembros_SesionDB { get; set; }
        public virtual DbSet<MiembrosDB> MiembrosDBs { get; set; }
        public virtual DbSet<Punto_AgendaDB> Punto_AgendaDB { get; set; }
        public virtual DbSet<PuntosXSesionDB> PuntosXSesionDBs { get; set; }
        public virtual DbSet<SesionDB> SesionDBs { get; set; }
        public virtual DbSet<SesionesXConsejoDB> SesionesXConsejoDBs { get; set; }
        public virtual DbSet<Solicitudes_PuntosDB> Solicitudes_PuntosDB { get; set; }
    
        public virtual int sp_AceptarSolicitud(string num_Sesion, Nullable<decimal> id_Punto)
        {
            var num_SesionParameter = num_Sesion != null ?
                new ObjectParameter("Num_Sesion", num_Sesion) :
                new ObjectParameter("Num_Sesion", typeof(string));
    
            var id_PuntoParameter = id_Punto.HasValue ?
                new ObjectParameter("id_Punto", id_Punto) :
                new ObjectParameter("id_Punto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AceptarSolicitud", num_SesionParameter, id_PuntoParameter);
        }
    
        public virtual ObjectResult<sp_ActaSesion_Result> sp_ActaSesion(string num_Sesion)
        {
            var num_SesionParameter = num_Sesion != null ?
                new ObjectParameter("Num_Sesion", num_Sesion) :
                new ObjectParameter("Num_Sesion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ActaSesion_Result>("sp_ActaSesion", num_SesionParameter);
        }
    
        public virtual int sp_ActualizarMiembro(string correo1, string correo2, string nombre, string tipoMiembro)
        {
            var correo1Parameter = correo1 != null ?
                new ObjectParameter("correo1", correo1) :
                new ObjectParameter("correo1", typeof(string));
    
            var correo2Parameter = correo2 != null ?
                new ObjectParameter("correo2", correo2) :
                new ObjectParameter("correo2", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var tipoMiembroParameter = tipoMiembro != null ?
                new ObjectParameter("tipoMiembro", tipoMiembro) :
                new ObjectParameter("tipoMiembro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarMiembro", correo1Parameter, correo2Parameter, nombreParameter, tipoMiembroParameter);
        }
    
        public virtual ObjectResult<sp_AdjuntosXPunto_Result> sp_AdjuntosXPunto(Nullable<decimal> id_Punto)
        {
            var id_PuntoParameter = id_Punto.HasValue ?
                new ObjectParameter("id_Punto", id_Punto) :
                new ObjectParameter("id_Punto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AdjuntosXPunto_Result>("sp_AdjuntosXPunto", id_PuntoParameter);
        }
    
        public virtual ObjectResult<sp_Agenda_Result> sp_Agenda(string num_Sesion)
        {
            var num_SesionParameter = num_Sesion != null ?
                new ObjectParameter("Num_Sesion", num_Sesion) :
                new ObjectParameter("Num_Sesion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Agenda_Result>("sp_Agenda", num_SesionParameter);
        }
    
        public virtual ObjectResult<sp_AgendaSesion_Result> sp_AgendaSesion(string num_Sesion)
        {
            var num_SesionParameter = num_Sesion != null ?
                new ObjectParameter("Num_Sesion", num_Sesion) :
                new ObjectParameter("Num_Sesion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AgendaSesion_Result>("sp_AgendaSesion", num_SesionParameter);
        }
    
        public virtual ObjectResult<sp_ComentariosXPunto_Result> sp_ComentariosXPunto(Nullable<decimal> id_Punto)
        {
            var id_PuntoParameter = id_Punto.HasValue ?
                new ObjectParameter("id_Punto", id_Punto) :
                new ObjectParameter("id_Punto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ComentariosXPunto_Result>("sp_ComentariosXPunto", id_PuntoParameter);
        }
    
        public virtual ObjectResult<sp_MiembrosXConsejo_Result> sp_MiembrosXConsejo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MiembrosXConsejo_Result>("sp_MiembrosXConsejo");
        }
    
        public virtual ObjectResult<sp_MiembrosXSesion_Result> sp_MiembrosXSesion(string num_Sesion)
        {
            var num_SesionParameter = num_Sesion != null ?
                new ObjectParameter("Num_Sesion", num_Sesion) :
                new ObjectParameter("Num_Sesion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MiembrosXSesion_Result>("sp_MiembrosXSesion", num_SesionParameter);
        }
    
        public virtual int sp_MoverPuntoAgenda(string num_Sesion, Nullable<decimal> nuevaPos, Nullable<decimal> viejaPos)
        {
            var num_SesionParameter = num_Sesion != null ?
                new ObjectParameter("Num_Sesion", num_Sesion) :
                new ObjectParameter("Num_Sesion", typeof(string));
    
            var nuevaPosParameter = nuevaPos.HasValue ?
                new ObjectParameter("nuevaPos", nuevaPos) :
                new ObjectParameter("nuevaPos", typeof(decimal));
    
            var viejaPosParameter = viejaPos.HasValue ?
                new ObjectParameter("viejaPos", viejaPos) :
                new ObjectParameter("viejaPos", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MoverPuntoAgenda", num_SesionParameter, nuevaPosParameter, viejaPosParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_NextIDComentario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_NextIDComentario");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_NextIDPunto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_NextIDPunto");
        }
    
        public virtual int sp_nuevaActualizacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_nuevaActualizacion");
        }
    
        public virtual int sp_NuevaSesion(string numero, Nullable<System.DateTime> fecha, string lugar)
        {
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NuevaSesion", numeroParameter, fechaParameter, lugarParameter);
        }
    
        public virtual ObjectResult<sp_SesionesxConsejo_Result> sp_SesionesxConsejo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SesionesxConsejo_Result>("sp_SesionesxConsejo");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_Solicitudes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Solicitudes");
        }
    
        public virtual ObjectResult<sp_Solicitudes1_Result> sp_Solicitudes1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Solicitudes1_Result>("sp_Solicitudes1");
        }
    
        public virtual ObjectResult<sp_MiembrosXSesion1_Result> sp_MiembrosXSesion1(string num_Sesion)
        {
            var num_SesionParameter = num_Sesion != null ?
                new ObjectParameter("Num_Sesion", num_Sesion) :
                new ObjectParameter("Num_Sesion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MiembrosXSesion1_Result>("sp_MiembrosXSesion1", num_SesionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_ConsejoActual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_ConsejoActual");
        }
    }
}
