//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto1DB : DbContext
    {
        public Proyecto1DB()
            : base("name=Proyecto1DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActaXSesion> ActaXSesions { get; set; }
        public virtual DbSet<AdjuntosXPunto> AdjuntosXPuntoes { get; set; }
        public virtual DbSet<Comentario> Comentarios { get; set; }
        public virtual DbSet<ComentariosXPunto> ComentariosXPuntoes { get; set; }
        public virtual DbSet<Consejo> Consejoes { get; set; }
        public virtual DbSet<Miembro> Miembros { get; set; }
        public virtual DbSet<Miembros_Consejo> Miembros_Consejo { get; set; }
        public virtual DbSet<Miembros_Sesion> Miembros_Sesion { get; set; }
        public virtual DbSet<Punto_Agenda> Punto_Agenda { get; set; }
        public virtual DbSet<PuntosXSesion> PuntosXSesions { get; set; }
        public virtual DbSet<Sesion> Sesions { get; set; }
        public virtual DbSet<Solicitudes_Puntos> Solicitudes_Puntos { get; set; }
    }
}
