//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComentariosDB()
        {
            this.ComentariosXPuntoDBs = new HashSet<ComentariosXPuntoDB>();
        }
    
        public decimal id_Comentario { get; set; }
        public string miembro { get; set; }
        public string contenido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosXPuntoDB> ComentariosXPuntoDBs { get; set; }
        public virtual MiembrosDB MiembrosDB { get; set; }
    }
}
