//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocXSesionDB
    {
        public decimal id_DocXSesion { get; set; }
        public string sesion { get; set; }
        public string nombreArchivo { get; set; }
        public byte[] contenido { get; set; }
        public string tipo { get; set; }
    
        public virtual SesionDB SesionDB { get; set; }
    }
}
