//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembros_ConsejoDB
    {
        public decimal id_Miembros_Consejo { get; set; }
        public Nullable<decimal> id_Consejo { get; set; }
        public string miembro { get; set; }
    
        public virtual ConsejoDB ConsejoDB { get; set; }
        public virtual MiembrosDB MiembrosDB { get; set; }
    }
}
