//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembros_SesionDB
    {
        public decimal id_Miembros_Sesion { get; set; }
        public string sesion { get; set; }
        public string miembro { get; set; }
        public string estadoAsistencia { get; set; }
    
        public virtual MiembrosDB MiembrosDB { get; set; }
        public virtual SesionDB SesionDB { get; set; }
    }
}
