//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiembrosDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MiembrosDB()
        {
            this.ComentariosDBs = new HashSet<ComentariosDB>();
            this.HistorialMiembrosDBs = new HashSet<HistorialMiembrosDB>();
            this.Miembros_ConsejoDB = new HashSet<Miembros_ConsejoDB>();
            this.Miembros_SesionDB = new HashSet<Miembros_SesionDB>();
        }
    
        public string correo1 { get; set; }
        public string correo2 { get; set; }
        public string nombre { get; set; }
        public string tipoMiembro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosDB> ComentariosDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialMiembrosDB> HistorialMiembrosDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miembros_ConsejoDB> Miembros_ConsejoDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miembros_SesionDB> Miembros_SesionDB { get; set; }
    }
}
