//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punto_AgendaDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Punto_AgendaDB()
        {
            this.AdjuntosXPuntoDBs = new HashSet<AdjuntosXPuntoDB>();
            this.ComentariosXPuntoDBs = new HashSet<ComentariosXPuntoDB>();
            this.Solicitudes_PuntosDB = new HashSet<Solicitudes_PuntosDB>();
            this.PuntosXSesionDBs = new HashSet<PuntosXSesionDB>();
        }
    
        public decimal id_Punto { get; set; }
        public string nombre { get; set; }
        public string resultandos { get; set; }
        public string considerandos { get; set; }
        public string seAcuerda { get; set; }
        public Nullable<decimal> votosAFavor { get; set; }
        public Nullable<decimal> votosEnContra { get; set; }
        public Nullable<decimal> votosAbstenciones { get; set; }
        public string tipoPunto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjuntosXPuntoDB> AdjuntosXPuntoDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosXPuntoDB> ComentariosXPuntoDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes_PuntosDB> Solicitudes_PuntosDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntosXSesionDB> PuntosXSesionDBs { get; set; }
    }
}
