//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punto_Agenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Punto_Agenda()
        {
            this.AdjuntosXPuntoes = new HashSet<AdjuntosXPunto>();
            this.ComentariosXPuntoes = new HashSet<ComentariosXPunto>();
            this.Solicitudes_Puntos = new HashSet<Solicitudes_Puntos>();
            this.PuntosXSesions = new HashSet<PuntosXSesion>();
        }
    
        public decimal id_Punto { get; set; }
        public string nombre { get; set; }
        public string resultandos { get; set; }
        public string considerandos { get; set; }
        public string seAcuerda { get; set; }
        public Nullable<decimal> votosAFavor { get; set; }
        public Nullable<decimal> votosEnContra { get; set; }
        public Nullable<decimal> votosAbstenciones { get; set; }
        public string tipoPunto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjuntosXPunto> AdjuntosXPuntoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosXPunto> ComentariosXPuntoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes_Puntos> Solicitudes_Puntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntosXSesion> PuntosXSesions { get; set; }
    }
}
